data:
  image: debian:jessie
  user: www-data
  volumes:
    - .:/var/www/

web:
  image: nginx:1.7
  ports:
    - "8016:80"
    - "44312:443"
  links:
    - php
  volumes:
    - docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - data

php:
  build: docker/php
  links:
    - db
  volumes_from:
    - data

composer:
  build: docker/composer
  volumes_from:
    - data

artisan:
  build: docker/artisan
  links:
    - db
  volumes_from:
    - data

db:
  image: mysql:5.6
  volumes:
    - docker/db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: database
    MYSQL_USER: database
    MYSQL_PASSWORD: database

adminer:
  image: louisbl/adminer:4.1.0
  ports:
    - "8015:80"
  links:
    - db
